/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the category list */
        get: operations["getCategories"];
        put?: never;
        /** Create a category at the end of the list */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace the complete category order */
        put: operations["reorderCategories"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/{categoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a category and uncategorize its root tasks */
        delete: operations["deleteCategory"];
        options?: never;
        head?: never;
        /** Rename a category */
        patch: operations["renameCategory"];
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get every saved task tree */
        get: operations["getTaskTrees"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{rootId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Create or replace a complete task tree */
        put: operations["saveTaskTree"];
        post?: never;
        /** Delete a complete task tree */
        delete: operations["deleteTaskTree"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{rootId}/category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Assign or remove a root task category */
        patch: operations["setTaskCategory"];
        trace?: never;
    };
    "/api/tasks/proposals/breakdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Propose immediate children for an actionable task
         * @description The proposal does not modify the draft. A saved draft requires an authenticated owner.
         */
        post: operations["proposeTaskBreakdown"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/proposals/durations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Propose missing durations for a task subtree
         * @description The proposal does not modify the draft. A saved draft requires an authenticated owner.
         */
        post: operations["proposeTaskDurations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/proposals/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Propose a dependency-aware order for immediate children
         * @description The proposal does not modify the draft or move tasks to another parent. A saved draft requires an authenticated owner.
         */
        post: operations["proposeTaskOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Category: {
            /** Format: uuid */
            id: string;
            name: string;
            position: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CategoryList: {
            /** Format: uuid */
            id: string;
            name: string;
            position: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        }[];
        ProblemDetails: {
            type: string;
            title: string;
            status: number;
            detail: string;
            instance: string;
            retryable: boolean;
        };
        TaskNode: {
            /** Format: uuid */
            id: string;
            title: string;
            durationSeconds: number | null;
            children: components["schemas"]["TaskNode"][];
        };
        TaskTreeDraft: {
            /** Format: uuid */
            id: string;
            title: string;
            durationSeconds: number | null;
            children: components["schemas"]["TaskNode"][];
            /** Format: uuid */
            categoryId?: string | null;
            revision: number | null;
        };
        TaskTree: {
            /** Format: uuid */
            id: string;
            title: string;
            durationSeconds: number | null;
            children: components["schemas"]["TaskNode"][];
            /** Format: uuid */
            categoryId: string | null;
            revision: number;
        };
        TaskBreakdownProposal: {
            /** Format: uuid */
            taskId: string;
            children: {
                /** Format: uuid */
                id: string;
                title: string;
            }[];
        };
        TaskDurationProposal: {
            /** Format: uuid */
            taskId: string;
            durations: {
                /** Format: uuid */
                taskId: string;
                durationSeconds: number;
            }[];
        };
        OrderOptimizationProposal: {
            /** Format: uuid */
            taskId: string;
            orderedTaskIds: string[];
        };
        TaskCategoryAssignment: {
            /** Format: uuid */
            rootId: string;
            /** Format: uuid */
            categoryId: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Categories in persistent position order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string;
                        position: number;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    }[];
                };
            };
            /** @description Authentication is required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description The request rate limit was exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description The request could not be completed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description The created category */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string;
                        position: number;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
            /** @description The category is invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description Authentication is required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description The category conflicts with current category data */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description The request rate limit was exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description The request could not be completed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
        };
    };
    reorderCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    categoryIds: string[];
                };
            };
        };
        responses: {
            /** @description The reordered category list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string;
                        position: number;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    }[];
                };
            };
            /** @description The category order is invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description Authentication is required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description The category list has changed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description The request rate limit was exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description The request could not be completed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
        };
    };
    deleteCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                categoryId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The category was deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authentication is required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description The category does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description The request rate limit was exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description The request could not be completed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
        };
    };
    renameCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                categoryId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description The renamed category */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string;
                        position: number;
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
            /** @description The category is invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description Authentication is required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description The category does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description The category name conflicts with another category */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description The request rate limit was exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description The request could not be completed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
        };
    };
    getTaskTrees: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Saved task trees ordered newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        title: string;
                        durationSeconds: number | null;
                        children: components["schemas"]["TaskNode"][];
                        /** Format: uuid */
                        categoryId: string | null;
                        revision: number;
                    }[];
                };
            };
            /** @description Authentication is required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description The request rate limit was exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description The request could not be completed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
        };
    };
    saveTaskTree: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rootId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    id: string;
                    title: string;
                    durationSeconds: number | null;
                    children: components["schemas"]["TaskNode"][];
                    /** Format: uuid */
                    categoryId?: string | null;
                    revision: number | null;
                };
            };
        };
        responses: {
            /** @description The saved task tree */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        title: string;
                        durationSeconds: number | null;
                        children: components["schemas"]["TaskNode"][];
                        /** Format: uuid */
                        categoryId: string | null;
                        revision: number;
                    };
                };
            };
            /** @description The task tree is invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description Authentication is required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description The task tree does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description The task tree revision conflicts with the saved revision */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description The request rate limit was exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description The request could not be completed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
        };
    };
    deleteTaskTree: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rootId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    revision: number;
                };
            };
        };
        responses: {
            /** @description The task tree was deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The request is invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description Authentication is required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description The task tree does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description The task tree revision conflicts with the saved revision */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description The request rate limit was exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description The request could not be completed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
        };
    };
    setTaskCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rootId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    categoryId: string | null;
                };
            };
        };
        responses: {
            /** @description The root task category assignment */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        rootId: string;
                        /** Format: uuid */
                        categoryId: string | null;
                    };
                };
            };
            /** @description The category assignment is invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description Authentication is required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description The root task or category does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description The request rate limit was exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description The request could not be completed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
        };
    };
    proposeTaskBreakdown: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    draft: {
                        /** Format: uuid */
                        id: string;
                        title: string;
                        durationSeconds: number | null;
                        children: components["schemas"]["TaskNode"][];
                        /** Format: uuid */
                        categoryId?: string | null;
                        revision: number | null;
                    };
                    /** Format: uuid */
                    taskId: string;
                    detail: 1 | 2 | 3 | 4 | 5;
                };
            };
        };
        responses: {
            /** @description A one-level task breakdown proposal */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        taskId: string;
                        children: {
                            /** Format: uuid */
                            id: string;
                            title: string;
                        }[];
                    };
                };
            };
            /** @description The task-tree draft is invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description Authentication is required for this saved task tree */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description The selected task or saved task tree does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description The saved task tree revision has changed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description The AI request rate limit was exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description AI generation is not configured correctly */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description AI generation returned an invalid response */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description AI generation is temporarily unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description AI generation timed out */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
        };
    };
    proposeTaskDurations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    draft: {
                        /** Format: uuid */
                        id: string;
                        title: string;
                        durationSeconds: number | null;
                        children: components["schemas"]["TaskNode"][];
                        /** Format: uuid */
                        categoryId?: string | null;
                        revision: number | null;
                    };
                    /** Format: uuid */
                    taskId: string;
                };
            };
        };
        responses: {
            /** @description Duration proposals for actionable tasks missing a duration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        taskId: string;
                        durations: {
                            /** Format: uuid */
                            taskId: string;
                            durationSeconds: number;
                        }[];
                    };
                };
            };
            /** @description The task-tree draft is invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description Authentication is required for this saved task tree */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description The selected task or saved task tree does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description The saved task tree revision has changed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description The AI request rate limit was exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description AI generation is not configured correctly */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description AI generation returned an invalid response */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description AI generation is temporarily unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description AI generation timed out */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
        };
    };
    proposeTaskOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    draft: {
                        /** Format: uuid */
                        id: string;
                        title: string;
                        durationSeconds: number | null;
                        children: components["schemas"]["TaskNode"][];
                        /** Format: uuid */
                        categoryId?: string | null;
                        revision: number | null;
                    };
                    /** Format: uuid */
                    taskId: string;
                };
            };
        };
        responses: {
            /** @description A proposed sibling order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        taskId: string;
                        orderedTaskIds: string[];
                    };
                };
            };
            /** @description The task-tree draft is invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description Authentication is required for this saved task tree */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description The selected task or saved task tree does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description The saved task tree revision has changed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description The AI request rate limit was exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description AI generation is not configured correctly */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description AI generation returned an invalid response */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description AI generation is temporarily unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
            /** @description AI generation timed out */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail: string;
                        instance: string;
                        retryable: boolean;
                    };
                };
            };
        };
    };
}
